version: '3.8'
services:
  db:
    image: postgres
    container_name: monorepo_todo_app_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: monorepo_todo_app
      POSTGRES_PASSWORD: development
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: monorepo_todo_app_pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: development@monorepo.com
      PGADMIN_DEFAULT_PASSWORD: development
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
